version: '3.8'
networks:
    ntwk:
        driver: bridge

services:
  wordpress:
    build:
      context: .
      dockerfile: ./docker/wordpress/Dockerfile
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: user
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_NAME: wordpress
      WP_ENVIRONMENT: development
      WP_DISABLE_COOKIE_CHECK: "true"
      COOKIE_DOMAIN: localhost
    depends_on:
      - db
    networks:
      - ntwk

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - type: tmpfs
        target: /var/lib/mysql
#      - ./local-data/db_mysql:/var/lib/mysql
      - ./docker/db/init:/docker-entrypoint-initdb.d
    networks:
      - ntwk

  playwrite:
    build:
      context: .
      dockerfile: ./docker/playwrite/Dockerfile
    environment:
      - WP_URL=http://wordpress:80
    depends_on:
      - wordpress
    networks:
      - ntwk
