name: CI for WordPress with Playwright

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      db:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: wordpress
          MYSQL_USER: user
          MYSQL_PASSWORD: password
        options: >
          --health-cmd="mysqladmin ping -h localhost -u user --password=password"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
          -v /docker/db/init:/docker-entrypoint-initdb.d

      wordpress:
        image: wordpress:latest
        ports:
          - 8080:80
        env:
          WORDPRESS_DB_HOST: db:3306
          WORDPRESS_DB_USER: user
          WORDPRESS_DB_PASSWORD: password
          WORDPRESS_DB_NAME: wordpress
          WP_ENVIRONMENT: development
          WP_DISABLE_COOKIE_CHECK: "true"
          COOKIE_DOMAIN: localhost
        options: >
          -v /wordpress/wp-content:/var/www/html/wp-content

    steps:
    # Checkout do código
    - name: Checkout repository
      uses: actions/checkout@v3

    # Esperar os serviços estarem prontos
    - name: Wait for WordPress
      run: |
        for i in {1..30}; do
          if curl -s http://localhost:8080 > /dev/null; then
            echo "WordPress is up!"
            break
          fi
          echo "Waiting for WordPress..."
          sleep 5
        done

    - name: SO dependencies
      run: |
        sudo apt-get update
        sudo add-apt-repository universe
        sudo add-apt-repository multiverse
        sudo apt-get update        
        sudo apt-get install -y \
          libwoff1 \ 
          libopus0 \
          libvpx7 \
          libevent-2.1-7 \ 
          libgstapp-1.0-0 \
          libgstpbutils-1.0-0 \
          libgstreamer-plugins-base1.0-dev \ 
          libgstreamer1.0-0 \
          libharfbuzz-icu0 \
          libhyphen0 \
          libgles2 \
          libflite1 \
          libx264-164\ 
          libmanette-0.2-0


    # Instalar dependências do Playwright
    - name: Install Node Dependencies
      working-directory: playwright
      run: npm install

    - name: Install Playwright Dependencies
      working-directory: playwright
      run: npx playwright install

    # Executar os testes Playwright
    - name: Run Playwright Tests
      working-directory: playwright
      env:
        WP_URL: http://localhost:8080
      run: npx playwright test