name: CI for WordPress with Playwright

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      db:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: wordpress
          MYSQL_USER: user
          MYSQL_PASSWORD: password
        options: >
          --health-cmd="mysqladmin ping -h localhost -u user --password=password"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
          -v "docker/db/init:/docker-entrypoint-initdb.d"

      wordpress:
        image: wordpress:latest
        ports:
          - 8080:80
        env:
          WORDPRESS_DB_HOST: db:3306
          WORDPRESS_DB_USER: user
          WORDPRESS_DB_PASSWORD: password
          WORDPRESS_DB_NAME: wordpress
          WP_ENVIRONMENT: development
          WP_DISABLE_COOKIE_CHECK: "true"
          COOKIE_DOMAIN: localhost
        options: >
          -v "wordpress/wp-content:/var/www/html/wp-content"

    steps:
    # Checkout do código
    - name: Checkout repository
      uses: actions/checkout@v3

    # Esperar o serviço MySQL estar pronto
    - name: Wait for MySQL
      run: |
        for i in {1..30}; do
          if mysqladmin ping -h 127.0.0.1 -uuser --password=password --silent; then
            echo "MySQL is up!"
            break
          fi
          echo "Waiting for MySQL..."
          sleep 5
        done

    # Verificar se o .sql foi importado
    - name: Check SQL Import
      run: |
        mysql -h 127.0.0.1 -uuser --password=password wordpress -e "SHOW TABLES;"
        mysql -h 127.0.0.1 -uuser --password=password wordpress -e "SELECT * FROM wp_users;"
        

    # Esperar os serviços estarem prontos
    - name: Wait for WordPress
      run: |
        for i in {1..30}; do
          if curl -s http://localhost:8080 > /dev/null; then
            echo "WordPress is up!"
            break
          fi
          echo "Waiting for WordPress..."
          sleep 5
        done

    - name: SO dependencies
      run: |
        sudo apt-get update
        sudo add-apt-repository universe
        sudo add-apt-repository multiverse
        sudo apt-get update       
        sudo apt-get upgrade -y
        sudo apt-get install -f        
        sudo apt-get install -y \
          nodejs \
          libunwind-dev \
          libgstreamer-plugins-base1.0-dev \
          libgstreamer-plugins-good1.0-dev \
          libgstreamer-plugins-bad1.0-dev \
          libx264-dev


    # Instalar dependências do Playwright
    - name: Install Node Dependencies
      working-directory: playwright
      run: npm install

    - name: Install Playwright Dependencies
      working-directory: playwright
      run: npx playwright install

    # Executar os testes Playwright
    - name: Run Playwright Tests
      working-directory: playwright
      env:
        WP_URL: http://localhost:8080
      run: npx playwright test