name: CI for WordPress with Playwright

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # Checkout do código
    - name: Checkout repository
      uses: actions/checkout@v3

    # Instalar Docker Compose
    - name: Install Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose-plugin

    # Configurar Docker Compose
    - name: Set up Docker Compose
      run: docker compose -f docker-compose.yml up -d

    # Esperar os serviços estarem prontos
    - name: Wait for WordPress
      run: |
        for i in {1..30}; do
          if curl -s http://localhost:8080 > /dev/null; then
            echo "WordPress is up!"
            break
          fi
          echo "Waiting for WordPress..."
          sleep 5
        done

    # Instalar dependências do Playwright
    - name: Install Playwright Dependencies
      run: |
        cd path/to/playwright
        npm ci

    # Executar os testes Playwright
    - name: Run Playwright Tests
      env:
        WP_URL: http://localhost:8080
      run: npm test